services:
  api-mock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - billetera-seca_backend

networks:
  billetera-seca_backend:
    external: true